name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Build HTML
      run: |
        pip install -r requirements.txt
        make html
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
